# edX is currently using MySQL 5.6, which is not available on Xenial by default.
- name: Add PPA for MySQL 5.6
  apt_repository:
    repo: "ppa:ondrej/mysql-5.6"
    update_cache: yes

- name: Create mysql group
  group: name=mysql system=yes

- name: Create mysql user
  user: name=mysql group=mysql system=yes

- name: mount /var/lib/mysql
  mount: name=/var/lib/mysql src="{{MYSQL_OPENSTACK_DB_DEVICE}}" fstype=ext4 state=mounted

- name: chown -R /var/lib/mysql
  file: path=/var/lib/mysql owner=mysql group=mysql recurse=yes state=directory

- name: chmod /var/lib/mysql
  file: path=/var/lib/mysql mode=700 state=directory

- name: Allow required ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 3306


- name: Creating directories for Mysql file limit configurations
  file:
    path: /etc/systemd/system/mysql.service.d/
    state: directory
    mode: 0755
    owner: root
    group: root

# FIXME check that this file can be set up before mysql is installed, and then mysql won't overwrite it
- name: Set open file limit in systemd (LimitNOFILE)
  blockinfile:
    dest: /etc/systemd/system/mysql.service.d/override.conf
    create: yes
    owner: root
    group: root
    block: |
      # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
      [Service]
      LimitNOFILE=102400

# After being set, these settings can be confirmed by doing
# cat /proc/SOME_PID/limits
- name: Set open file limit in security/limits.d
  blockinfile:
    dest: /etc/security/limits.d/90-nproc.conf
    create: yes
    owner: root
    group: root
    block: |
      # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
      * soft nofile 102400
      * hard nofile 102400
      * soft nproc 10240
      * hard nproc 10240
      root soft nproc unlimited

# FIXME prepare a temporary file that will be used by the "mysql_config_include_files" setting (ansible-role-mysql role)
# It wil end up not in /etc/mysql/my.cnf but in /etc/my.cnf.d/open_files_limit.cnf
- name: Set open file limit in MySQL config
  blockinfile:
    dest: /tmp/mysql__open_files_limit.cnf
    create: yes
    owner: root
    group: root
    block: |
      # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
      open_files_limit = 102400

- name: Copy pre-backup script
  template:
    src: backup-pre-mysql.sh
    dest: /usr/local/sbin/backup-pre.sh
    owner: root
    group: root
    mode: "500"

- name: Copy post-backup script
  template:
    src: backup-post-mysql.sh
    dest: /usr/local/sbin/backup-post.sh
    owner: root
    group: root
    mode: "500"
