# edX is currently using MySQL 5.6, which is not available on Xenial by default.
- name: Add PPA for MySQL 5.6
  apt_repository:
    repo: "ppa:ondrej/mysql-5.6"
    update_cache: yes

- name: Create mysql group
  group: name=mysql system=yes

- name: Create mysql user
  user: name=mysql group=mysql system=yes

- name: mount /var/lib/mysql
  mount: name=/var/lib/mysql src="{{MYSQL_OPENSTACK_DB_DEVICE}}" fstype=ext4 state=mounted

- name: chown -R /var/lib/mysql
  file: path=/var/lib/mysql owner=mysql group=mysql recurse=yes state=directory

- name: chmod /var/lib/mysql
  file: path=/var/lib/mysql mode=700 state=directory

- name: Allow required ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 3306
#
# Parameters to set the maximum number of open files
#
- name: Creating directories for Mysql files limit configurations
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - /etc/mysql/conf.d/
    - /etc/systemd/system/mysql.service.d/

# 
# The numbers set in security/limits.d affect processes spawned by a login shell, but
# not those spawned by systemd/upstart.
# Ubuntu 14.04 uses upstart, Ubuntu 16.04 systemd.
- name: Set open files limit in mysql through systemd
  blockinfile:
    dest: /etc/systemd/system/mysql.service.d/override.conf
    create: yes
    owner: root
    group: root
    block: |
      # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
      [Service]
      LimitNOFILE={{ MYSQL_OPEN_FILES_LIMIT }}
      LimitNPROC={{ MYSQL_PROCESSES_LIMIT }}
#
# The "upstart" version is commented out because the presence of this small
#  /etc/init/mysql.conf prevents the real one from being installed in a later step
# (it ends in /etc/init/mysql.conf.dpkg-dist instead)
#
# - name: Set open files limit in mysql through upstart
#   blockinfile:
#     dest: /etc/init/mysql.conf
#     create: yes
#     owner: root
#     group: root
#     block: |
#       # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
#       limit nofile {{ MYSQL_OPEN_FILES_LIMIT }} {{ MYSQL_OPEN_FILES_LIMIT }}
#       limit nproc {{ MYSQL_PROCESSES_LIMIT }} {{ MYSQL_PROCESSES_LIMIT }}

# After being set, these settings can be confirmed by doing:
# cat /proc/SOME_PID/limits
- name: Set open files limit in security/limits.d
  blockinfile:
    dest: /etc/security/limits.d/90-nproc.conf
    create: yes
    owner: root
    group: root
    block: |
      # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
      * soft nofile {{ MYSQL_OPEN_FILES_LIMIT }}
      * hard nofile {{ MYSQL_OPEN_FILES_LIMIT }}
      * soft nproc {{ MYSQL_PROCESSES_LIMIT }}
      * hard nproc {{ MYSQL_PROCESSES_LIMIT }}
      root soft nproc unlimited

# After being set, this can be verified by logging in to mysql and doing:
#    show global variables like 'open%';
- name: Set open files limit in MySQL config
  blockinfile:
    dest: /etc/mysql/conf.d/open_files_limit.cnf
    create: yes
    owner: root
    group: root
    block: |
      # cf https://duntuk.com/how-raise-ulimit-open-files-and-mysql-openfileslimit
      [mysqld]
      open_files_limit = {{ MYSQL_OPEN_FILES_LIMIT }}

- name: Copy pre-backup script
  template:
    src: backup-pre-mysql.sh
    dest: /usr/local/sbin/backup-pre.sh
    owner: root
    group: root
    mode: "500"

- name: Copy post-backup script
  template:
    src: backup-post-mysql.sh
    dest: /usr/local/sbin/backup-post.sh
    owner: root
    group: root
    mode: "500"
